# Generated by Django 5.1.4 on 2025-02-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oem", "0002_job_alter_jobexecution_completed_at_technician_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicerequest",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("maintenance", "Maintenance"),
                    ("repair", "Repair"),
                    ("inspection", "Inspection"),
                    ("installation", "Installation"),
                ],
                max_length=100,
            ),
        ),
    ]
